<?php

/**
 * BaseReadedTickets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $ticket_id
 * @property Ticket $Ticket
 * @property sfGuardUser $User
 * 
 * @method integer       getUserId()    Returns the current record's "user_id" value
 * @method integer       getTicketId()  Returns the current record's "ticket_id" value
 * @method Ticket        getTicket()    Returns the current record's "Ticket" value
 * @method sfGuardUser   getUser()      Returns the current record's "User" value
 * @method ReadedTickets setUserId()    Sets the current record's "user_id" value
 * @method ReadedTickets setTicketId()  Sets the current record's "ticket_id" value
 * @method ReadedTickets setTicket()    Sets the current record's "Ticket" value
 * @method ReadedTickets setUser()      Sets the current record's "User" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReadedTickets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('readed_tickets');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ticket_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('unique_for_user_and_ticket', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'ticket_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ticket', array(
             'local' => 'ticket_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}