<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ticket_id
 * @property clob $text
 * @property string $attachment
 * @property enum $changed_ticket_state_to
 * @property ReadedComments $ReadedComments
 * @property sfGuardUser $sfGuardUser
 * @property Ticket $Ticket
 * 
 * @method integer        getTicketId()                Returns the current record's "ticket_id" value
 * @method clob           getText()                    Returns the current record's "text" value
 * @method string         getAttachment()              Returns the current record's "attachment" value
 * @method enum           getChangedTicketStateTo()    Returns the current record's "changed_ticket_state_to" value
 * @method ReadedComments getReadedComments()          Returns the current record's "ReadedComments" value
 * @method sfGuardUser    getSfGuardUser()             Returns the current record's "sfGuardUser" value
 * @method Ticket         getTicket()                  Returns the current record's "Ticket" value
 * @method Comment        setTicketId()                Sets the current record's "ticket_id" value
 * @method Comment        setText()                    Sets the current record's "text" value
 * @method Comment        setAttachment()              Sets the current record's "attachment" value
 * @method Comment        setChangedTicketStateTo()    Sets the current record's "changed_ticket_state_to" value
 * @method Comment        setReadedComments()          Sets the current record's "ReadedComments" value
 * @method Comment        setSfGuardUser()             Sets the current record's "sfGuardUser" value
 * @method Comment        setTicket()                  Sets the current record's "Ticket" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('ticket_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('attachment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('changed_ticket_state_to', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'opened',
              1 => 'closed',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ReadedComments', array(
             'local' => 'id',
             'foreign' => 'comment_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Ticket', array(
             'local' => 'ticket_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}