<?php

/**
 * BaseRefTicketResponsible
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ticket_id
 * @property integer $user_id
 * @property Ticket $Ticket
 * 
 * @method integer              getTicketId()  Returns the current record's "ticket_id" value
 * @method integer              getUserId()    Returns the current record's "user_id" value
 * @method Ticket               getTicket()    Returns the current record's "Ticket" value
 * @method RefTicketResponsible setTicketId()  Sets the current record's "ticket_id" value
 * @method RefTicketResponsible setUserId()    Sets the current record's "user_id" value
 * @method RefTicketResponsible setTicket()    Sets the current record's "Ticket" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefTicketResponsible extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_ticket_responsible');
        $this->hasColumn('ticket_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ticket', array(
             'local' => 'ticket_id',
             'foreign' => 'id'));
    }
}