<?php

/**
 * BasePeriods
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $period_name
 * @property clob $description
 * @property integer $length
 * @property Doctrine_Collection $Ticket
 * 
 * @method string              getPeriodName()  Returns the current record's "period_name" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method integer             getLength()      Returns the current record's "length" value
 * @method Doctrine_Collection getTicket()      Returns the current record's "Ticket" collection
 * @method Periods             setPeriodName()  Sets the current record's "period_name" value
 * @method Periods             setDescription() Sets the current record's "description" value
 * @method Periods             setLength()      Sets the current record's "length" value
 * @method Periods             setTicket()      Sets the current record's "Ticket" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeriods extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periods');
        $this->hasColumn('period_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('length', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ticket', array(
             'local' => 'id',
             'foreign' => 'period_id'));
    }
}