<?php

/**
 * BaseRefCompanyResponsible
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $user_id
 * @property sfGuardGroup $Company
 * @property sfGuardUser $Responsible
 * 
 * @method integer               getGroupId()     Returns the current record's "group_id" value
 * @method integer               getUserId()      Returns the current record's "user_id" value
 * @method sfGuardGroup          getCompany()     Returns the current record's "Company" value
 * @method sfGuardUser           getResponsible() Returns the current record's "Responsible" value
 * @method RefCompanyResponsible setGroupId()     Sets the current record's "group_id" value
 * @method RefCompanyResponsible setUserId()      Sets the current record's "user_id" value
 * @method RefCompanyResponsible setCompany()     Sets the current record's "Company" value
 * @method RefCompanyResponsible setResponsible() Sets the current record's "Responsible" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefCompanyResponsible extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_company_responsible');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup as Company', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Responsible', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}