<?php

/**
 * PeriodsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeriodsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Periods');
    }
}