<?php

/**
 * ReadedTicketsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReadedTicketsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReadedTicketsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReadedTickets');
    }
}