<?php

/**
 * ReadedCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReadedCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReadedCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReadedComments');
    }
}