<?php

/**
 * RefCompanyNotifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefCompanyNotifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefCompanyNotifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefCompanyNotify');
    }
}