<?php

/**
 * RefCompanyNotifyEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefCompanyNotifyEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefCompanyNotifyEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefCompanyNotifyEmail');
    }
}