<?php

/**
 * RefTicketResponsible
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefTicketResponsible extends BaseRefTicketResponsible
{
  public function postInsert($event) {
    $responsible = Doctrine_Core::getTable('sfGuardUser')->find($this->getUserId());

    // send sms to responsible
    if ($responsible and $responsible->getPhone()) {
      Sms::send([$responsible->getPhone()], 'Вы были назначены ответственным за выполнение заявки ' . $this->getTicketId());
    }

    // add comment to ticket
    if ($responsible) {
      $comment = Comment::createFromArray([
        'ticket_id' => $this->getTicketId()
        , 'created_by' => $this->getCreatedBy()
        , 'text' => 'Добавил в список ответственных ' . $responsible
      ]);

      $comment->save();
    }
  }

  public function preDqlDelete($event) {
    $parameters = $event->getQuery()->getParams()['where'];
    $ticketId = array_shift($parameters);
    $usersIds = $parameters;

    foreach ($usersIds as $userId) {
      $responsible = Doctrine_Core::getTable('sfGuardUser')->find($userId);

      // add comment to ticket
      if ($responsible) {
        $comment = Comment::createFromArray([
          'ticket_id' => $ticketId
          , 'created_by' => sfContext::getInstance()->getUser()->getGuardUser()->getId()
          , 'text' => 'Убрал из списка ответственных ' . $responsible
        ]);

        $comment->save();
      }
    }
  }
}
