<?php

/**
 * RefTicketResponsibleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTicketResponsibleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTicketResponsibleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTicketResponsible');
    }
}