<?php

/**
 * RefTicketResponsible
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefTicketResponsible extends BaseRefTicketResponsible
{
  public function postInsert($event) {
    $responsible = Doctrine_Core::getTable('sfGuardUser')->find($this->getUserId());

    // send sms to responsible
    if ($responsible and $responsible->getPhone()) {
      file_get_contents("http://sms.ru/sms/send?api_id=ab037779-734f-3394-794f-7d532843ed95&to="
        . $responsible->getPhone() . "&from=f1lab&text="
        . urlencode('Вы были назначены ответственным за выполнение заявки ' . $this->getTicketId())
      );
    }
  }
}
