<?php

/**
 * RefTicketRepeaterResponsibleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTicketRepeaterResponsibleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTicketRepeaterResponsibleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTicketRepeaterResponsible');
    }
}