<?php

/**
 * RefTicketObserverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTicketObserverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTicketObserverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTicketObserver');
    }
}