<?php

/**
 * RefTicketRepeaterObserverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTicketRepeaterObserverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTicketRepeaterObserverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTicketRepeaterObserver');
    }
}