<?php

/**
 * RefTicketObserver
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefTicketObserver extends BaseRefTicketObserver
{
  public function postInsert($event) {
    $observer = Doctrine_Core::getTable('sfGuardUser')->find($this->getUserId());

    // add comment to ticket
    if ($observer) {
      $comment = Comment::createFromArray([
        'ticket_id' => $this->getTicketId()
        , 'created_by' => $this->getCreatedBy()
        , 'text' => 'Добавил в список наблюдателей ' . $observer
      ]);

      $comment->save();
    }
  }

  public function preDqlDelete($event) {
    $parameters = $event->getQuery()->getParams()['where'];
    $ticketId = array_shift($parameters);
    $usersIds = $parameters;

    foreach ($usersIds as $userId) {
      $observer = Doctrine_Core::getTable('sfGuardUser')->find($userId);

      // add comment to ticket
      if ($observer) {
        $comment = Comment::createFromArray([
          'ticket_id' => $ticketId
          , 'created_by' => sfContext::getInstance()->getUser()->getGuardUser()->getId()
          , 'text' => 'Убрал из списка наблюдателей ' . $observer
        ]);

        $comment->save();
      }
    }
  }
}
