<?php

/**
 * RefUserCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefUserCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefUserCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefUserCategory');
    }
}