<?php

/**
 * TicketRepeaterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketRepeaterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketRepeaterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketRepeater');
    }
}