<?php

/**
 * TicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketTable extends Doctrine_Table
{
   
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ticket');
    }

    public function getTicketsAll()
    {
      return $this->createQuery('a, a.Creator')->execute();
    }

    public function getTicketsOpened()
    {
      return $this->createQuery('a, a.Creator')->where('isClosed = ?', false)->execute();
    }

    public function getTicketsClosed()
    {
      return $this->createQuery('a, a.Creator')->where('isClosed = ?', true)->execute();
    }
}