<?php

/**
 * TicketRepeater
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TicketRepeater extends BaseTicketRepeater
{
  public function preInsert($event)
  {
    // just to pass not null constraint
    $this->setNextStart($this->getPlannedStart());
  }
}
