<?php

/**
 * Ticket
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ticket extends BaseTicket
{
  private function correctDeadline() {
    $deadline = $this->getDeadline();
    if ($deadline) {
      $this->setDeadline(date('Y.m.d 23:59', strtotime($deadline)));
    }
  }

  public function preInsert($event) {
    $this->correctDeadline();
  }

  public function preUpdate($event) {
    $this->correctDeadline();
  }
}
