# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /tickets/my
  param: { module: tickets, action: index, state: opened }

shedule-source:
  url:   /tickets/eventsource
  param: { module: tickets, action: eventSource}
 
shedule-modal:
  url:   /tickets/modal/:id
  param: { module: tickets, action: sheduleModal}
  requirements: { id: \d+ }

shedule-events:
  url:   /tickets/sheduleEvent
  param: { module: tickets, action: sheduleEvent}

shedule-events-new:
  url:   /tickets/sheduleEventNew
  param: { module: tickets, action: sheduleEventNew}  

ticket-done:
  url:   /tickets/done/:id
  param: { module: tickets, action: ticketDone}
  requirements: { id: \d+ }

tickets-my:
  url:   /tickets/my/:state
  param: { module: tickets, action: index, state: opened }
  requirements: { state: opened|closed|all }

tickets-company:
  url:   /tickets/company/:state
  param: { module: tickets, action: company, state: opened }
  requirements: { state: opened|closed|all }

tickets-new:
  url:   /tickets/new
  param: { module: tickets, action: new }

tickets-performed:
  url:   /tickets/performed/:id
  class:   sfDoctrineRoute
  options: { model: Ticket, type: object }
  param: { module: tickets, action: performed }
  requirements: { id: \d+ }
  
tickets-create:
  url:   /tickets/create
  param: { module: tickets, action: create }

tickets-show:
  url:   /tickets/:id
  param: { module: tickets, action: show }
  requirements: { id: \d+ }

tickets-delete:
  url:   /tickets/:id/delete
  param: { module: tickets, action: delete }
  requirements: { id: \d+ }

tickets-edit:
  url:   /tickets/:id/edit
  param: { module: tickets, action: edit }
  requirements: { id: \d+ }

tickets-update:
  url:   /tickets/:id/update
  param: { module: tickets, action: update }
  requirements: { id: \d+ }

comments-create:
  url:   /tickets/:id/comment
  param: { module: tickets, action: comment }
  requirements: { id: \d+ }

comments-delete:
  url:   /tickets/:id/comment/delete/:comment
  param: { module: tickets, action: commentDelete }
  requirements: { id: \d+, comment: \d+ }

redirectToHomepage:
  url:   /
  param: { module: redirector, action: index }

companies:
  url:   /companies
  param: { module: companies, action: index }

companies-show:
  url:   /companies/:id
  param: { module: companies, action: show }
  requirements: { id: \d+ }

companies-new:
  url:   /companies/new
  param: { module: companies, action: new }

companies-create:
  url:   /companies/create
  param: { module: companies, action: create }

companies-edit:
  url:   /companies/:id/edit
  param: { module: companies, action: edit }
  requirements: { id: \d+ }

companies-update:
  url:   /companies/:id/update
  param: { module: companies, action: update }
  requirements: { id: \d+ }

companies-delete:
  url:   /companies/:id/delete
  param: { module: companies, action: delete }
  requirements: { id: \d+ }

users:
  class: sfDoctrineRouteCollection
  options:
    model: sfGuardUser
    prefix_path: /sfGuardUser
    module: users

dashboard:
  url:   /dashboard
  param: { module: dashboard, action: index }

dashboard-tickets:
  url:   /dashboard/tickets/:state
  param: { module: dashboard, action: tickets, state: opened }
  requirements: { state: opened|closed|all }

dashboard-comments:
  url:   /dashboard/comments/:state
  param: { module: dashboard, action: comments, state: comments }
  requirements: { state: comments|all }
  
dashboard-settings:
  url:   /dashboard/settings
  param: { module: dashboard, action: settings, state: comments }

unread:
  url: /tickets/unread
  param: { module: tickets, action: unread }
 
shedule:
  url:  /shedule
  param: { module: tickets, action: shedule } 

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

