# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    viewport:      width=device-width, initial-scale=1.0

  stylesheets:
    - bootstrap
    - bootstrap-datepicker
    - fullcalendar
    - timepicker
    - datetimepicker
    - bootstrap-wysihtml5-0.0.2.css
    - chosen
    - style

    - /bower_components/select2/select2.css
    - /bower_components/angular-ui-select/dist/select.css

    - main

  javascripts:
    - wysihtml5.min.js
    - jquery.min.js
    - bootstrap-wysihtml5-0.0.2.js
    - bootstrap.min.js
    - bootstrap-datepicker
    - bootstrap-datetimepicker
    - bootstrap-datetimepicker.ru.js
    - bootstrap-timepicker
    - fullcalendar.min.js
    - jquery-ui.custom.min.js
    - chosen.jquery.min.js
    - jquery-migrate-1.2.1.min.js

    - /bower_components/angular/angular.min.js
    - /bower_components/ngstorage/ngStorage.js
    - /bower_components/coffee-script/extras/coffee-script.js
    - /bower_components/angular-ui-select/dist/select.js

    - main


  has_layout:     true
  layout:         layout
