<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardGroup extends PluginsfGuardGroup
{
  public function getUsersIds()
  {
    $q = Doctrine_Query::create()
      ->select('gug.user_id')
      ->from('sfGuardUserGroup gug')
      ->where('gug.group_id = ?', $this->getId())
      ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR) // return only array(0=>1, 1=>5, 2=>7)
    ;

    return (array)$q;
  }
}
