<?php

/**
 * BasesfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property boolean $isExecutor
 * @property boolean $isClient
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Responsibles
 * @property Doctrine_Collection $Notify
 * @property Doctrine_Collection $sfGuardGroupPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property Doctrine_Collection $RefCompanyResponsible
 * @property Doctrine_Collection $RefCompanyNotify
 * @property Doctrine_Collection $Ticket
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method boolean             getIsExecutor()             Returns the current record's "isExecutor" value
 * @method boolean             getIsClient()               Returns the current record's "isClient" value
 * @method Doctrine_Collection getUsers()                  Returns the current record's "Users" collection
 * @method Doctrine_Collection getPermissions()            Returns the current record's "Permissions" collection
 * @method Doctrine_Collection getResponsibles()           Returns the current record's "Responsibles" collection
 * @method Doctrine_Collection getNotify()                 Returns the current record's "Notify" collection
 * @method Doctrine_Collection getSfGuardGroupPermission() Returns the current record's "sfGuardGroupPermission" collection
 * @method Doctrine_Collection getSfGuardUserGroup()       Returns the current record's "sfGuardUserGroup" collection
 * @method Doctrine_Collection getRefCompanyResponsible()  Returns the current record's "RefCompanyResponsible" collection
 * @method Doctrine_Collection getRefCompanyNotify()       Returns the current record's "RefCompanyNotify" collection
 * @method Doctrine_Collection getTicket()                 Returns the current record's "Ticket" collection
 * @method sfGuardGroup        setName()                   Sets the current record's "name" value
 * @method sfGuardGroup        setDescription()            Sets the current record's "description" value
 * @method sfGuardGroup        setIsExecutor()             Sets the current record's "isExecutor" value
 * @method sfGuardGroup        setIsClient()               Sets the current record's "isClient" value
 * @method sfGuardGroup        setUsers()                  Sets the current record's "Users" collection
 * @method sfGuardGroup        setPermissions()            Sets the current record's "Permissions" collection
 * @method sfGuardGroup        setResponsibles()           Sets the current record's "Responsibles" collection
 * @method sfGuardGroup        setNotify()                 Sets the current record's "Notify" collection
 * @method sfGuardGroup        setSfGuardGroupPermission() Sets the current record's "sfGuardGroupPermission" collection
 * @method sfGuardGroup        setSfGuardUserGroup()       Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardGroup        setRefCompanyResponsible()  Sets the current record's "RefCompanyResponsible" collection
 * @method sfGuardGroup        setRefCompanyNotify()       Sets the current record's "RefCompanyNotify" collection
 * @method sfGuardGroup        setTicket()                 Sets the current record's "Ticket" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('isExecutor', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('isClient', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardGroupPermission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUser as Responsibles', array(
             'refClass' => 'RefCompanyResponsible',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUser as Notify', array(
             'refClass' => 'RefCompanyNotify',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('RefCompanyResponsible', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('RefCompanyNotify', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('Ticket', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}