<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('sf_guard_group', 'isexecutor', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_group', 'isclient', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}