<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ticket', 'deadline', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('ticket', 'deadline');
    }
}