<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('comment', 'text', 'clob', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}