<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ticket', 'attach', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('ticket', 'attach');
    }
}