<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ticket', 'deleted_at', 'timestamp', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('ticket', 'deleted_at');
    }
}