<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('readed_tickets', 'readed_tickets_ticket_id_ticket_id', array(
             'name' => 'readed_tickets_ticket_id_ticket_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket',
             ));
        $this->createForeignKey('readed_tickets', 'readed_tickets_user_id_sf_guard_user_id', array(
             'name' => 'readed_tickets_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('readed_tickets', 'readed_tickets_ticket_id', array(
             'fields' => 
             array(
              0 => 'ticket_id',
             ),
             ));
        $this->addIndex('readed_tickets', 'readed_tickets_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('readed_tickets', 'readed_tickets_ticket_id_ticket_id');
        $this->dropForeignKey('readed_tickets', 'readed_tickets_user_id_sf_guard_user_id');
        $this->removeIndex('readed_tickets', 'readed_tickets_ticket_id', array(
             'fields' => 
             array(
              0 => 'ticket_id',
             ),
             ));
        $this->removeIndex('readed_tickets', 'readed_tickets_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}