<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ref_company_responsible', 'ref_company_responsible_group_id_sf_guard_group_id', array(
             'name' => 'ref_company_responsible_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             ));
        $this->createForeignKey('ref_company_responsible', 'ref_company_responsible_user_id_sf_guard_user_id', array(
             'name' => 'ref_company_responsible_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('ref_ticket_responsible', 'ref_ticket_responsible_ticket_id_ticket_id', array(
             'name' => 'ref_ticket_responsible_ticket_id_ticket_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket',
             ));
        $this->addIndex('ref_company_responsible', 'ref_company_responsible_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('ref_company_responsible', 'ref_company_responsible_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('ref_ticket_responsible', 'ref_ticket_responsible_ticket_id', array(
             'fields' => 
             array(
              0 => 'ticket_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ref_company_responsible', 'ref_company_responsible_group_id_sf_guard_group_id');
        $this->dropForeignKey('ref_company_responsible', 'ref_company_responsible_user_id_sf_guard_user_id');
        $this->dropForeignKey('ref_ticket_responsible', 'ref_ticket_responsible_ticket_id_ticket_id');
        $this->removeIndex('ref_company_responsible', 'ref_company_responsible_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('ref_company_responsible', 'ref_company_responsible_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('ref_ticket_responsible', 'ref_ticket_responsible_ticket_id', array(
             'fields' => 
             array(
              0 => 'ticket_id',
             ),
             ));
    }
}