<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('readed_comments', 'unique_for_user_and_ticket', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'comment_id',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('readed_comments', 'unique_for_user_and_comment', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'comment_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->addIndex('readed_comments', 'unique_for_user_and_ticket', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'comment_id',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('readed_comments', 'unique_for_user_and_comment', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'comment_id',
             ),
             'type' => 'unique',
             ));
    }
}