<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('readed_comments', 'readed_comments_comment_id_comment_id', array(
             'name' => 'readed_comments_comment_id_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             ));
        $this->addIndex('readed_comments', 'readed_comments_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('readed_comments', 'readed_comments_comment_id_comment_id');
        $this->removeIndex('readed_comments', 'readed_comments_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }
}