<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('shedule', 'shedule_user_id_sf_guard_user_id', array(
             'name' => 'shedule_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('shedule', 'shedule_period_id_periods_id', array(
             'name' => 'shedule_period_id_periods_id',
             'local' => 'period_id',
             'foreign' => 'id',
             'foreignTable' => 'periods',
             ));
        $this->addIndex('shedule', 'shedule_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('shedule', 'shedule_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('shedule', 'shedule_user_id_sf_guard_user_id');
        $this->dropForeignKey('shedule', 'shedule_period_id_periods_id');
        $this->removeIndex('shedule', 'shedule_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('shedule', 'shedule_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }
}