<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shedule', 'company_id', 'integer', '8', array(
             ));
        $this->changeColumn('shedule', 'task', 'clob', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('shedule', 'company_id');
    }
}