<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ticket', 'ticket_period_id_periods_id', array(
             'name' => 'ticket_period_id_periods_id',
             'local' => 'period_id',
             'foreign' => 'id',
             'foreignTable' => 'periods',
             ));
        $this->addIndex('ticket', 'ticket_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ticket', 'ticket_period_id_periods_id');
        $this->removeIndex('ticket', 'ticket_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }
}