<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('shedule');
        $this->addColumn('ticket', 'campany_id', 'integer', '8', array(
        ));
    }

    public function down()
    {
        $this->createTable('shedule', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'task' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'company_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'period_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->removeColumn('ticket', 'campany_id'); 
    }
}