<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ticket', 'ticket_campany_id_sf_guard_group_id', array(
             'name' => 'ticket_campany_id_sf_guard_group_id',
             'local' => 'campany_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             ));
        $this->addIndex('ticket', 'ticket_campany_id', array(
             'fields' => 
             array(
              0 => 'campany_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ticket', 'ticket_campany_id_sf_guard_group_id');
        $this->removeIndex('ticket', 'ticket_campany_id', array(
             'fields' => 
             array(
              0 => 'campany_id',
             ),
             ));
    }
}