<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('comment', 'changed_ticket_state_to', 'enum', '', array(
             'values' =>
             array(
              0 => 'opened',
              1 => 'applied',
              2 => 'closed',
             ),
             ));
    }

    public function down()
    {

    }
}
