<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'type', 'enum', '', array(
             'values' =>
             array(
              0 => 'it-admin',
              1 => 'user',
             ),
             'notnull' => '1',
             'default' => 'user',
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'type');
    }
}
