<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version38 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ticket', 'ticket_category_id_category_id', array(
             'name' => 'ticket_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->addIndex('ticket', 'ticket_category_id', array(
             'fields' =>
             array(
              0 => 'category_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ticket', 'ticket_category_id_category_id');
        $this->removeIndex('ticket', 'ticket_category_id', array(
             'fields' =>
             array(
              0 => 'category_id',
             ),
             ));
    }
}
