<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version55 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comment', 'skip_notification', 'boolean', '25', array(
             'notnull' => '1',
             'default' => 'false',
             ));
    }

    public function down()
    {
        $this->removeColumn('comment', 'skip_notification');
    }
}
