<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('readed_comments', 'readed_comments_ticket_id_ticket_id', array(
             'name' => 'readed_comments_ticket_id_ticket_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket',
             ));
        $this->addIndex('readed_comments', 'readed_comments_ticket_id', array(
             'fields' =>
             array(
              0 => 'ticket_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('readed_comments', 'readed_comments_ticket_id_ticket_id');
        $this->removeIndex('readed_comments', 'readed_comments_ticket_id', array(
             'fields' =>
             array(
              0 => 'ticket_id',
             ),
             ));
    }
}
