<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version57 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_group', 'deadline_for_setting_responsible', 'integer', '8', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addColumn('sf_guard_group', 'deadline_for_approving', 'integer', '8', array(
             'default' => '0',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_group', 'deadline_for_setting_responsible');
        $this->removeColumn('sf_guard_group', 'deadline_for_approving');
    }
}
