<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comment', 'is_remote', 'boolean', '25', array(
             'default' => 'true',
             'notnull' => '1',
             ));
        $this->addColumn('ticket', 'is_closed_remotely', 'boolean', '25', array(
             'default' => 'true',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('comment', 'is_remote');
        $this->removeColumn('ticket', 'is_closed_remotely');
    }
}
