<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ticket', 'ticket_repeater_id_ticket_repeater_id', array(
             'name' => 'ticket_repeater_id_ticket_repeater_id',
             'local' => 'repeater_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket_repeater',
             ));
        $this->addIndex('ticket', 'ticket_repeater_id', array(
             'fields' =>
             array(
              0 => 'repeater_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ticket', 'ticket_repeater_id_ticket_repeater_id');
        $this->removeIndex('ticket', 'ticket_repeater_id', array(
             'fields' =>
             array(
              0 => 'repeater_id',
             ),
             ));
    }
}
