<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version64 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('ref_ticket_repeater_observer', 'ref_ticket_repeater_observer_ticket_id_ticket_id');
        $this->dropForeignKey('ref_ticket_repeater_responsible', 'ref_ticket_repeater_responsible_ticket_id_ticket_id');
        $this->createForeignKey('ref_ticket_repeater_observer', 'ref_ticket_repeater_observer_ticket_id_ticket_repeater_id', array(
             'name' => 'ref_ticket_repeater_observer_ticket_id_ticket_repeater_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket_repeater',
             ));
        $this->createForeignKey('ref_ticket_repeater_responsible', 'ref_ticket_repeater_responsible_ticket_id_ticket_repeater_id', array(
             'name' => 'ref_ticket_repeater_responsible_ticket_id_ticket_repeater_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket_repeater',
             ));
    }

    public function down()
    {
        $this->createForeignKey('ref_ticket_repeater_observer', 'ref_ticket_repeater_observer_ticket_id_ticket_id', array(
             'name' => 'ref_ticket_repeater_observer_ticket_id_ticket_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket',
             ));
        $this->createForeignKey('ref_ticket_repeater_responsible', 'ref_ticket_repeater_responsible_ticket_id_ticket_id', array(
             'name' => 'ref_ticket_repeater_responsible_ticket_id_ticket_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket',
             ));
        $this->dropForeignKey('ref_ticket_repeater_observer', 'ref_ticket_repeater_observer_ticket_id_ticket_repeater_id');
        $this->dropForeignKey('ref_ticket_repeater_responsible', 'ref_ticket_repeater_responsible_ticket_id_ticket_repeater_id');
    }
}
