<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version62 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ticket', 'repeater_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('ticket', 'repeater_id');
    }
}
