<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version65 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ticket_repeater', 'isclosed', 'boolean', '25', array(
             'default' => 'false',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('ticket_repeater', 'isclosed');
    }
}
