<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version67 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_group', 'working_hours_from', 'string', '', array(
             'notnull' => '',
             ));
        $this->addColumn('sf_guard_group', 'working_hours_to', 'string', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_group', 'working_hours_from');
        $this->removeColumn('sf_guard_group', 'working_hours_to');
    }
}