<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('work', 'planned_at');
    }

    public function down()
    {
        $this->addColumn('work', 'planned_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }
}