<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version71 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('work', 'work_ticket_id_ticket_id', array(
             'name' => 'work_ticket_id_ticket_id',
             'local' => 'ticket_id',
             'foreign' => 'id',
             'foreignTable' => 'ticket',
             ));
        $this->addIndex('work', 'work_ticket_id', array(
             'fields' => 
             array(
              0 => 'ticket_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('work', 'work_ticket_id_ticket_id');
        $this->removeIndex('work', 'work_ticket_id', array(
             'fields' => 
             array(
              0 => 'ticket_id',
             ),
             ));
    }
}