<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version70 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('work', 'ticket_id', 'int', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('work', 'ticket_id');
    }
}