<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version75 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('work', 'started_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('work', 'finished_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}